### ISSUE TITLE
Specify which access are needed for the Github token

### ISSUE THREAD

**Issue by pascalandy** [itsksaurabh/doact#11]
In the read me I don't see what should we enable when creating the token.

![Screen Shot 2020-04-27 at 10 09 13 PM](https://user-images.githubusercontent.com/6694151/80439143-d1597800-88d3-11ea-8d14-e90849039292.jpg)

Thanks!

**Comment by itsksaurabh** [comment]
@pascalandy Sir, According to the [official documentation](https://developer.github.com/v3/actions/self-hosted-runners/), Access tokens require repo scope for private repos and public_repo scope for public repos. GitHub Apps must have the administration permission for repositories or the organization_self_hosted_runners permission for organizations. Authenticated users must have admin access to the repository or organization to use this API.
I will mention it in the readme for sure. Thanks! :)
