### ISSUE TITLE
Error if SSH key already on account

### ISSUE THREAD

**Issue by MattIPv4** [itsksaurabh/doact#8]
👋 Thanks for putting this together, it is incredibly useful!

One small thing that's a bit annoying, if the SSH key already exists on your DO account, terraform will fail when it tries to create the new SSH key.

Maybe it'd be best to provide an option to supply the name of an existing SSH key to use instead of adding a new one?

**Comment by itsksaurabh** [comment]
@MattIPv4 I am really glad that you liked my efforts and found Doact useful. I appreciate that you raised this issue and completely agree with your point. I will work on it asap. 
If you loved Doact and found it useful then please share it. 😊
